### ISSUE TITLE
Series subtypes are missing

### ISSUE THREAD

**Issue by bpetridean** [ascendtech/gwt-highcharts#3]
In scope of Highcharts js library [Series](https://api.highcharts.com/highcharts/series) type  is used as the base class for all chart types, thus containing diff properties with respect to the type of chart chosen.
Let's take [Sankey](https://api.highcharts.com/highcharts/series.sankey)/[Organization](https://api.highcharts.com/highcharts/series.organization) for example: the `series` model contains, besides the `data` prop, a `nodes` prop, enabling the dev to use it in order to declare the nodes, while the data prop is used to define the connections/edges.
Now, is there a way to achieve the above through gwt-highcharts  (in it's current version)? Maybe through the use of `data` only?
If not, will the above be supported in a future version?

Thanks!

**Comment by payammeyer** [comment]
@bpetridean thanks for the note. I believe at the time of my wrapping of the library, Sankey or other network type charts didn't exist yet. I will try to get the extra properties added. In the meantime, you should be able to just extend the Series class and add the missing properties and it should just work.

**Comment by payammeyer** [comment]
4341fabd3ee60aad298723da19664adbc977c7d4 should address this, version 1.2.1 released. I haven't tested, so I hope it works. Please let me know.
