### ISSUE TITLE
Syntax error introduced in version 1.2.1

### ISSUE THREAD

**Issue by bpetridean** [ascendtech/gwt-highcharts#4]
See comment below: 
https://github.com/ascendtech/gwt-highcharts/commit/4341fabd3ee60aad298723da19664adbc977c7d4#diff-1447757ab4edb22f637d98091451cca8f188da2293a3997dec8e92df8c411dbaR18

**Comment by payammeyer** [comment]
Looks like I missed the annotation on that one, 1.2.2 released, thanks for pointing it out.

**Comment by bpetridean** [comment]
Oops, you forgot to make the overlay method as `final`

https://github.com/ascendtech/gwt-highcharts/commit/bf90af3d4b2312900ccedce056764aff81e2b87a#diff-1447757ab4edb22f637d98091451cca8f188da2293a3997dec8e92df8c411dbaR19

**Comment by payammeyer** [comment]
Urgh... it's from when my IDE wasn't setup, I'll fix it.

**Comment by payammeyer** [comment]
1.2.3 with a facepalm...
